# Module 2 – Data Analysis with Python

In this module, I learned how to analyse datasets using Pandas and NumPy.

## Topics Covered

- Importing CSV files
- Exploring datasets
- Selecting rows and columns
- Filtering data
- Sorting data
- Basic statistical analysis
- Handling missing values
- Grouping data
- NumPy arrays and operations

## Practice Project

Hollywood Movies Data Analysis

In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv("/content/Datasets.csv")

print(data)

                     Movie      Genre  Year  Rating  Budget
0                Inception     Sci-Fi  2010     8.8     160
1             Interstellar     Sci-Fi  2014     8.7     165
2                   Avatar     Action  2009     7.9     237
3                  Titanic    Romance  1997     7.8     200
4          The Dark Knight     Action  2008     9.0     185
5                    Joker      Drama  2019     8.4      55
6                     Dune     Sci-Fi  2021     8.0     165
7                   Frozen  Animation  2013     7.4     150
8                Gladiator     Action  2000     8.5     103
9               The Matrix     Sci-Fi  1999     8.7      63
10        Avengers Endgame     Action  2019     8.4     356
11           The Lion King  Animation  1994     8.5      45
12             Oppenheimer      Drama  2023     8.6     100
13               Toy Story  Animation  1995     8.3      30
14           The Godfather      Crime  1972     9.2       6
15                Parasite   Thriller  2

In [3]:
data.shape
data.head()
data.tail()
data.columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Movie   20 non-null     object 
 1   Genre   20 non-null     object 
 2   Year    20 non-null     int64  
 3   Rating  20 non-null     float64
 4   Budget  20 non-null     int64  
dtypes: float64(1), int64(2), object(2)
memory usage: 932.0+ bytes


In [4]:
data.describe()

,Year,Rating,Budget
count,20.000000,20.000000,20.00000
mean,2008.800000,8.335000,134.75000
std,13.032752,0.481527,87.34377
min,1972.000000,7.300000,6.00000
25%,1999.750000,8.150000,61.00000
50%,2011.500000,8.400000,155.00000
75%,2019.000000,8.625000,188.75000
max,2023.000000,9.200000,356.00000


In [5]:
Movie=data["Movie"]
Genres=data["Genre"]
Rating=data["Rating"]
year=data["Year"]
Budget=data["Budget"]

In [40]:
print("Rating columns:\n")
print(Rating)

Rating columns:

0     8.8
1     8.7
2     7.9
3     7.8
4     9.0
5     8.4
6     8.0
7     7.4
8     8.5
9     8.7
10    8.4
11    8.5
12    8.6
13    8.3
14    9.2
15    8.5
16    8.3
17    7.3
18    8.2
19    8.2
Name: Rating, dtype: float64


In [41]:
print("Rating Greater than 8 or not:\n")
print(Rating>8)

Rating Greater than 8 or not:

0      True
1      True
2     False
3     False
4      True
5      True
6     False
7     False
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17    False
18     True
19     True
Name: Rating, dtype: bool


In [42]:
print("Datas with rating greater than 8:\n")
print(data[Rating>8])

Datas with rating greater than 8:

                     Movie      Genre  Year  Rating  Budget
0                Inception     Sci-Fi  2010     8.8     160
1             Interstellar     Sci-Fi  2014     8.7     165
4          The Dark Knight     Action  2008     9.0     185
5                    Joker      Drama  2019     8.4      55
8                Gladiator     Action  2000     8.5     103
9               The Matrix     Sci-Fi  1999     8.7      63
10        Avengers Endgame     Action  2019     8.4     356
11           The Lion King  Animation  1994     8.5      45
12             Oppenheimer      Drama  2023     8.6     100
13               Toy Story  Animation  1995     8.3      30
14           The Godfather      Crime  1972     9.2       6
15                Parasite   Thriller  2019     8.5      11
16        Top Gun Maverick     Action  2022     8.3     170
18            Finding Nemo  Animation  2003     8.2      94
19  Spider-Man No Way Home     Action  2021     8.2     200


In [43]:
print("Sorted based on rating:\n")
print(data.sort_values("Rating"))

Sorted based on rating:

                     Movie      Genre  Year  Rating  Budget
17           Black Panther     Action  2018     7.3     200
7                   Frozen  Animation  2013     7.4     150
3                  Titanic    Romance  1997     7.8     200
2                   Avatar     Action  2009     7.9     237
6                     Dune     Sci-Fi  2021     8.0     165
18            Finding Nemo  Animation  2003     8.2      94
19  Spider-Man No Way Home     Action  2021     8.2     200
13               Toy Story  Animation  1995     8.3      30
16        Top Gun Maverick     Action  2022     8.3     170
5                    Joker      Drama  2019     8.4      55
10        Avengers Endgame     Action  2019     8.4     356
11           The Lion King  Animation  1994     8.5      45
15                Parasite   Thriller  2019     8.5      11
8                Gladiator     Action  2000     8.5     103
12             Oppenheimer      Drama  2023     8.6     100
1             I

In [51]:
print("In Decending:\n")
print(data.sort_values("Rating",ascending=False))

In Decending:

                     Movie      Genre  Year  Rating  Budget
14           The Godfather      Crime  1972     9.2       6
4          The Dark Knight     Action  2008     9.0     185
0                Inception     Sci-Fi  2010     8.8     160
1             Interstellar     Sci-Fi  2014     8.7     165
9               The Matrix     Sci-Fi  1999     8.7      63
12             Oppenheimer      Drama  2023     8.6     100
8                Gladiator     Action  2000     8.5     103
15                Parasite   Thriller  2019     8.5      11
11           The Lion King  Animation  1994     8.5      45
5                    Joker      Drama  2019     8.4      55
10        Avengers Endgame     Action  2019     8.4     356
13               Toy Story  Animation  1995     8.3      30
16        Top Gun Maverick     Action  2022     8.3     170
18            Finding Nemo  Animation  2003     8.2      94
19  Spider-Man No Way Home     Action  2021     8.2     200
6                     Dun

In [45]:
print("Groupby year with avg rating:\n")
data.groupby("Year")["Rating"].mean()

Groupby year with avg rating:



,Rating
Year,
1972,9.200000
1994,8.500000
1995,8.300000
1997,7.800000
1999,8.700000
2000,8.500000
2003,8.200000
2008,9.000000
2009,7.900000


In [46]:
print("with genre:\n")
data.groupby("Genre")["Rating"].mean()

with genre:



,Rating
Genre,
Action,8.228571
Animation,8.100000
Crime,9.200000
Drama,8.500000
Romance,7.800000
Sci-Fi,8.550000
Thriller,8.500000


In [47]:
print("counts per year:\n")
data["Year"].value_counts()

counts per year:



,count
Year,
2019,3
2021,2
2010,1
2014,1
2009,1
2008,1
1997,1
2013,1
2000,1


In [48]:
print("Check miss values:\n")
data.isna()

Check miss values:



,Movie,Genre,Year,Rating,Budget
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
5,False,False,False,False,False
6,False,False,False,False,False
7,False,False,False,False,False
8,False,False,False,False,False
9,False,False,False,False,False


In [49]:
print("using loc to identify the movie:\n")
data.loc[17,"Movie"]

using loc to identify the movie:



'Black Panther'

In [50]:
print("show the list of datas from 0 to 5:\n")
data.iloc[0:6]

show the list of datas from 0 to 5:



,Movie,Genre,Year,Rating,Budget
0,Inception,Sci-Fi,2010,8.8,160
1,Interstellar,Sci-Fi,2014,8.7,165
2,Avatar,Action,2009,7.9,237
3,Titanic,Romance,1997,7.8,200
4,The Dark Knight,Action,2008,9.0,185
5,Joker,Drama,2019,8.4,55


In [28]:
print("Highet Rating Index of movie:",data["Rating"].idxmax())

Highet Rating Index of movie: 14


In [29]:

print("Lowest Rating movie:",data.loc[data["Rating"].idxmin(), "Movie"])

Lowest Rating movie: Black Panther


In [30]:
print("Highest Rating movie:",data.loc[data["Rating"].idxmax(), "Movie"])

Highest Rating movie: The Godfather


In [31]:
print("Highest Budget:",data.loc[data["Budget"].idxmax(), "Movie"])

Highest Budget: Avengers Endgame


In [32]:
print("Lowest budget:",data.loc[data["Budget"].idxmin(), "Movie"])

Lowest budget: The Godfather


In [33]:
print("Oldest movie:",data.loc[data["Year"].idxmin(),"Movie"])

Oldest movie: The Godfather


In [34]:
print("Newest movie:",data.loc[data["Year"].idxmax(),"Movie"])

Newest movie: Oppenheimer


In [52]:
print("Total Number of Movies:",data["Movie"].count())

Total Number of Movies: 20


In [53]:
ratings = np.array([8.8, 8.6, 8.4, 8.0, 7.9])
print("Array like ratings:\n")
print(ratings)

Array like ratings:

[8.8 8.6 8.4 8.  7.9]


In [54]:
print("Basic operation:\n")
print(ratings + 1)
print(ratings - 1)
print(ratings * 2)
print(ratings / 2)

Basic operation:

[9.8 9.6 9.4 9.  8.9]
[7.8 7.6 7.4 7.  6.9]
[17.6 17.2 16.8 16.  15.8]
[4.4  4.3  4.2  4.   3.95]


In [55]:
print("Imp functions:\n")
print("Highest Rating:", np.max(ratings))
print("Lowest Rating:", np.min(ratings))
print("Average Rating:", np.mean(ratings))
print("Total Movies:", np.size(ratings))

Imp functions:

Highest Rating: 8.8
Lowest Rating: 7.9
Average Rating: 8.34
Total Movies: 5


In [56]:
print("Indexing:\n")
print(ratings[0])
print(ratings[2])

Indexing:

8.8
8.4


In [57]:
print("Two Dimensions Array:\n")
movie_data = np.array([
    [2010, 8.8],
    [2014, 8.6],
    [2009, 8.4],
    [2010, 8.0]
])

print(movie_data)
print(movie_data.shape)
print(movie_data.ndim)

Two Dimensions Array:

[[2010.     8.8]
 [2014.     8.6]
 [2009.     8.4]
 [2010.     8. ]]
(4, 2)
2
